### PR TITLE
additional options for RequireSsl

### PR DESCRIPTION
**Pull request by qbikez**
Added three additional opitons to RequireSslOptions:
* AllowHttp - allow http traffic, while enforcing SSL client certificate (for testing purposes)
* WriteReasonToContent - write ReasonPhrase to Response Content - see the reason in the browser immediately
* RequiredCertificateIssuer - require Client Certificate to be issued by a specific Authority

### CODE REVIEW

**Comment by lennybacon** [comment]
I would not compare against issuer name as I can use MakeCert.exe/OpenSSL to create a self signed certificate matching the criteria...

    if (cert.IssuerName.Name != _options.RequiredCertificateIssuer)

**Comment by lennybacon** [comment]
>> AllowHttp - allow http traffic, while enforcing SSL client certificate (for testing purposes)
The requirement of a Client Certificates is part of the SSL Handshake - As far as I can see you just allow HTTP for debugging...

**Comment by qbikez** [comment]
> I would not compare against issuer name as I can use MakeCert.exe/OpenSSL to create a self signed certificate matching the criteria

I have (incorrectly) assumed that this code can be reached only if the client certificate is valid (certificate issuer is a trusted root). 
I added `cert.Verify()` before IssuerName comparison to make sure the certificate is trusted.

**Comment by leastprivilege** [comment]
I opened a new PR. have a look,

**Pull request closed without merging**
